gomods/athens-charts

charts/athens-proxy/Chart.yaml, charts/athens-proxy/templates/_helpers.tpl, charts/athens-proxy/templates/deployment.yaml, charts/athens-proxy/values.yaml
This PR adds support for non-root containers to the helm chart.
A new bool value `image.runAsNonRoot` (default: false) was added, and when set to true, will add a `securityContext` to use the user and group `1000` as well as switching the home directory from `/root` to `/home/athens`.
This PR is dependent on the [non-root PR](https://github.com/gomods/athens/pull/1843) being merged and a new athens release.
=> feat: allow to run as non-root

charts/athens-proxy/Chart.yaml, charts/athens-proxy/templates/hpa.yaml, charts/athens-proxy/values.yaml
Autoscaling values must be integers, percents are not working.
We deploy athens proxy through ArgoCD. ArgoCD always shows the difference and wants to change memory with cpu utilization specification. In fact, it is the same, so let's change their order.
=> fix: use integer values for hpa, refactor for argocd

.github/dependabot.yaml
closes https://github.com/gomods/athens-charts/issues/17
solution is taken from https://github.com/gomods/athens/pull/1835/files
=> chore: add dependabot for up-to-date github actions

charts/athens-proxy/templates/config-ssh-git-servers.yaml
22 is the default SSH port and I reckon can be used in most cases.
I just thought that we could simplify a little bit configuration by removing parameter that is always the same :)
=> Add default SSH port

charts/athens-proxy/ci/basic-values.yaml, charts/athens-proxy/templates/_helpers.tpl, charts/athens-proxy/templates/config-ssh-git-servers.yaml, charts/athens-proxy/templates/config-upstream.yaml, charts/athens-proxy/templates/deployment.yaml, charts/athens-proxy/templates/hpa.yaml, charts/athens-proxy/templates/ingress.yaml, charts/athens-proxy/templates/jaeger-deploy.yaml, charts/athens-proxy/templates/jaeger-svc.yaml, charts/athens-proxy/templates/secret-ssh-git-servers.yaml, charts/athens-proxy/templates/secret.yaml, charts/athens-proxy/templates/service-account.yaml, charts/athens-proxy/templates/service-monitor.yaml, charts/athens-proxy/templates/service-scrape.yaml, charts/athens-proxy/templates/service.yaml, charts/athens-proxy/templates/storage-pvc.yaml, charts/athens-proxy/values.yaml
Resolves #44 
This chart appears to have the standard labels used with helm 2. This adds in the new helm 3 standard labels and also allows the user to pass in additional labels that will get applied to all resources. 
- Create a template helper that creates metadata labels that can be reused by multiple resource templates
- Include the existing labels in this helper for passivity
- default to use the fullName value for the name labels but allow an optional `appSuffix` to be passed in for passivity for the jaeger and storage usecases
- include this new helper in some resources that were missing the common labels
- add a helm value to pass in an object of custom labels which is a common helm convention
- enable jaeger and pass custom labels in CI to exercise more code paths
Run `helm …
=> Add new standard labels and allow custom labels

.github/workflows/ct.yaml, charts/athens-proxy/Chart.yaml, charts/athens-proxy/ci/basic-values.yaml, charts/athens-proxy/templates/deployment.yaml, charts/athens-proxy/values.yaml
Resolves issue: https://github.com/gomods/athens-charts/issues/49.
This PR updates the chart to enable us to override/set additional security context configuration at the container level in each of the containers in the athens-proxy deployment template. 
It moves the existing `securityContext` configuration to the `PodSecurityContext` at the pod spec level to ensure this isn't a breaking change and ensures backwards compatibility. It adds two new values in the chart `securityContext` (for the main athens container) and `initContainerSecurityContext` (for the init container, if used). This allows us to override/modify the existing configuration with additional security context configuration options in each of the containers, at the container `securityContext` level. 
See …
=> chore: enable container security contexts modifications

charts/athens-proxy/Chart.yaml
=> chore: update to athens v0.13.1

charts/athens-proxy/Chart.yaml, charts/athens-proxy/templates/secret-ssh-git-servers.yaml
Fixes #53 by removing the dash that trims the prefix.
Manifest generated using version 0.9.1:
```
kind: Secret
apiVersion: v1
metadata:
name: athens-athens-proxy-ssh-git-servers
labels:
app: athens-athens-proxy
chart: athens-proxy-0.9.1
release: "athens"
heritage: "Helm"
app.kubernetes.io/name: athens-athens-proxy
helm.sh/chart: athens-proxy-0.9.1
app.kubernetes.io/managed-by: "Helm"
app.kubernetes.io/instance: "athens"
app.kubernetes.io/version: "v0.13.1"
type: Opaque
data:id_rsa-sample.server.com: "LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KUkVEQUNURUQKLS0tLS1FTkQgT1BFTlNTSCBQUklWQVRFIEtFWS0tLS0tCg=="
```
Manifest generated after the fix:
```
kind: Secret
apiVersion: v1
metadata:
name: athens-athens-proxy-ssh-git-servers
labels:
app: athens-athens-proxy
chart: athens-proxy-0.9.1 …
```
=> Fix SSH Git Servers secret

charts/athens-proxy/Chart.yaml, charts/athens-proxy/templates/deployment.yaml, charts/athens-proxy/values.yaml
We run athens using this helm chart and would like to change its priority class in the cluster. 
- create a new value that defaults to empty
- passively only add the priority class if specified
- include an update to the Chart.yaml to trigger a release
```
❯ helm template charts/athens-proxy | grep priority
❯ helm template charts/athens-proxy --set priorityClassName=critical | grep priority
priorityClassName: "critical"
```
=> Allow setting a priority class name

README.md, renovate.json
doc: update Readme on the release process
=> fix: Post-upgrade tasks can only be used on self-hosted Renovate

charts/athens-proxy/templates/deployment.yaml
Horizontal Pod Autoscalers automatically change the `replicas` field based on runtime metrics of the application.
This can cause false warnings to appear for folks using GitOps tooling such as ArgoCD because the tool will indicate that the application is out-of-sync due to this field when it actually isn't.
This PR cleans up the deployment object so that it's not marked as Out-Of-Sync
=> fix: don't specify replicas when autoscaling is enabled

charts/athens-proxy/Chart.yaml, charts/athens-proxy/templates/_helpers.tpl, charts/athens-proxy/templates/deployment.yaml, charts/athens-proxy/templates/service-account.yaml, charts/athens-proxy/values.yaml
#71 excludes serviceAccounts in the deployment template entirely if `serviceAccount.enabled` is set to false, meaning it defaults to "default" for the deployment. Previously, we could create a service account that was named identical to `fullname`, i.e., either the release name or an override via values, and have that SA be used for the pod.
This PR re-adds the ability to use service accounts in the deployment *without* creating one, and also extends upon the pre-#71 behavior of allowing you to set the name of the service account to use via `serviceAccount.name`. The property is not set in the chart's default values, and defaults to the `fullname` behavior of < v0.9.4.
Additionally, we also swapped out a bunch of "templates" for "includes", as per …
=> fix: preprovisioned service account unable to be included in deployment

charts/athens-proxy/Chart.yaml, charts/athens-proxy/values.yaml
sshGitServers is a list not a dict, so the default value shouldn't be a dictionary.
=> #75: sshGitServers is a list not a dict

charts/athens-proxy/templates/service-monitor.yaml
Currently, when we define label under `metrics.serviceMonitor.labels` it won't work. This PR will fix this issue.
=> fix label overriding on service monitor

charts/athens-proxy/README.md, charts/athens-proxy/templates/deployment.yaml, charts/athens-proxy/values.yaml
=> Support external tracing deployment

charts/athens-proxy/Chart.yaml, charts/athens-proxy/templates/deployment.yaml, charts/athens-proxy/values.yaml
Use readiness probe parameters from values.
In some cases it's required to adjust the default probe parameters and currently this is only possible for the liveness probe.
=> Allow configuring readiness probe through values

.github/workflows/docs.yaml, charts/athens-proxy/README.md, charts/athens-proxy/README.md.gotmpl
Using `helm-docs` (https://github.com/norwoodj/helm-docs)
=> :memo: check for updated docs in pipeline

charts/athens-proxy/Chart.yaml, charts/athens-proxy/README.md, charts/athens-proxy/templates/deployment.yaml, charts/athens-proxy/values.yaml
Resolves issue #106
This adds the ability to add extra init containers to the athens proxy. I'm using a credentials-helper to provide authentication to the git repositories for athens. Using an init container can ensure the volumes are set up correctly.
Also adding clarification to the existing initContainer configuration 'initContainerSecurityContext' and 'intiContainerResources' to indicate they only apply to the 'sshGitServer' init container.
=> Addition of configurable init containers to athens-proxy

charts/athens-proxy/Chart.yaml, charts/athens-proxy/README.md, charts/athens-proxy/ci/basic-values.yaml, charts/athens-proxy/templates/deployment.yaml, charts/athens-proxy/values.yaml
https://github.com/gomods/athens-charts/issues/108
Modify the athens-chart to provide an option to configure `lifecycle` hook and `terminationGracePeriodSeconds`. Set the default value of `terminationGracePeriodSeconds` to be 30 seconds as it's the default value in Kubernetes.
=> allow setting lifecycle hook and terminationGracePeriodSeconds

charts/athens-proxy/Chart.yaml, charts/athens-proxy/README.md, charts/athens-proxy/ci/basic-values.yaml, charts/athens-proxy/templates/deployment.yaml, charts/athens-proxy/templates/secret.yaml, charts/athens-proxy/values.yaml
https://github.com/gomods/athens-charts/issues/111
Provide options to set Athens single flight configurations in the helm chart and store redis passwords as secrets. 
Bump the chart version to 0.14.8.
=> Add options to set Athens single flight configs and create passwords in secrets.yml
